export const RoomTypes: Record<string, string> = {
  "Living Room": "",
  "Bedroom": "",
  "Kitchen": "",
  "Dining Room": "",
  "Bathroom": "",
  "Home Office": "",
  "Game Room": "",
  "Library": "",
  "Home Theater": "",
  "Laundry Room": "",
  "Mudroom": "",
  "Sunroom": "",
  "Patio": "",
  "Sun room": "",
}

export const RoomStyles: Record<string, string> = {
  "Modern": "modern style",
  "Contemporary": "contemporary style",
  "Traditional": "traditional style",
  "Rustic": "rustic style",
  "Farmhouse": "farmhouse style",
  "Industrial": "industrial style",
  "Scanidnavian": "scandinavian style",
  "Mid-Century Modern": "mid-century modern styled patterns",
  "Bohemian": "bohemian style",
  "Coastal": "coastal style",
  "Mediterranean": "mediterranean style",
  "Tropical": "tropical style",
  "Glam": "glam style",
  "Minimalist": "minimalist style",
  "Eclectic": "eclectic style",
  "Transitional": "transitional styled simple lines",
  "Desert Retreat": "desert retreat style",
  "Urban": "urban style",
  "Shabby Chic": "shabby chic style",
  "Mountain Haven": "mountain haven style",
  "Morooccan Mystique": "moroccan style",
  "French Country": "french country style",
  "Mediterrean Retreat": "mediterrean style",
  "Hollywood Regency": "hollywood regency style",
  "Victorian": "victorian style",
  "Cottage": "cottage style",
  "Asian": "asian style",
  "Craftsman": "craftsman style",
  "Southwestern": "southwestern style",
}
