import type { Metadata } from "next";
import { Gabarito as FontSans } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";
import { cn } from "@/lib/utils";
import { AppHeader } from "@/components/app-header";
import { Footer } from "@/components/footer";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning data-theme="light">
        <body className={cn("min-h-screen font-sans flex flex-col antialiased", fontSans.variable)}>
          <AppHeader />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
